### PR TITLE
Fix issue - #10 : Error Handling When Deleting an Event

### LINKED ISSUE #10: IMPROVE - Error Handling When Deleting an Event
## Describe the feature you to improve
* The `deleteEvent` function in the `DashboardViewModel` doesn't handle errors and uses `try?`
* Use a do-catch block for this instead, and show an alert with the error's localized description, if something fails

### PR DESCRIPTION
**Pull request by Dishant10**
# What it Does
* Closes #10
* Handled error in func deleteEvent, added do catch block and added two variables which are responsible for showing an alert and error message with that alert. 

# How I Tested
* Tested by setting the showAlert variable to true while deleting an event and the alert was showing as soon as the an event was deleted from the list.

# Notes
* Anything else that should be noted about how you implemented this feature?

# Screenshot
* This is not a feature but a simple case of error handling hence I do not know what to screenshot and add here. Let me if there's a specific test or use case I'll definitely add that.

### CODE REVIEW

File: Basic-Car-Maintenance/Shared/Dashboard/ViewModels/DashboardViewModel.swift [hunk 1]
```diff
@@ -15,6 +15,8 @@ class DashboardViewModel: ObservableObject {
     let authenticationViewModel: AuthenticationViewModel
     
     @Published var events = [MaintenanceEvent]()
+    @Published var showErrorAlert = false
+    @Published var errorDeleting : Error?
```
Comment (mikaelacaron) [inline Basic-Car-Maintenance/Shared/Dashboard/ViewModels/DashboardViewModel.swift]: Can you rename this `errorMessage`

File: Basic-Car-Maintenance/Shared/Dashboard/ViewModels/DashboardViewModel.swift [hunk 2]
```diff
@@ -59,10 +61,17 @@ class DashboardViewModel: ObservableObject {
...
+            try await Firestore
+                .firestore()
+                .collection("maintenance_events")
+                .document(documentId)
+                .delete()
+        }
+        catch{
+            showErrorAlert.toggle()
+            errorDeleting = error
+            //print("Error : \(error.localizedDescription)")
```
Comment (mikaelacaron) [inline Basic-Car-Maintenance/Shared/Dashboard/ViewModels/DashboardViewModel.swift]: Add a space between the curly brace and the words `do` and `catch`, and put the would catch on the line with the brace `}`
Also can you use the error's `localizedDescription`?

The statement would look like this
```swift
do {
} catch {
}
```

File: Basic-Car-Maintenance/Shared/Dashboard/Views/DashboardView.swift [hunk 3]
```diff
@@ -50,6 +50,13 @@ struct DashboardView: View {
                     
                 }
             }
+            .alert("Failed To Delete Event", isPresented: $viewModel.showErrorAlert, actions: {
+                Button("OK") {
+                    viewModel.showErrorAlert = false
+                }
+            }, message: {
+                Text(viewModel.errorDeleting?.localizedDescription ?? "Error while deleting event").padding()
```
Comment (mikaelacaron) [inline Basic-Car-Maintenance/Shared/Dashboard/Views/DashboardView.swift]: As noted above just pass the localized description, and handle the optional in the view model rather than here in the view
(This would mean the `errorDeleting` would actually end up being a `String` rather than `Error`)

**Review by mikaelacaron — CHANGES_REQUESTED** [review]
Great work! Just a few changes, thanks!

When you've made the changes, click the "re-request" review button
Re-review button

File: Basic-Car-Maintenance/Shared/Dashboard/Views/DashboardView.swift (hunk 3 above)
Comment (Dishant10) [reply Basic-Car-Maintenance/Shared/Dashboard/Views/DashboardView.swift]: Got it! Pushed the code with the suggested changes. Let me know if the code needs more changes.

File: Basic-Car-Maintenance/Shared/Dashboard/ViewModels/DashboardViewModel.swift [hunk 4]
```diff
@@ -52,17 +54,23 @@ class DashboardViewModel: ObservableObject {
...
+            try await Firestore
+                .firestore()
+                .collection("maintenance_events")
+                .document(documentId)
+                .delete()
+            errorMessage = ""
+        } catch {
+            showErrorAlert.toggle()
+            errorMessage = error.localizedDescription
+            //print("Error : \(error.localizedDescription)")
```
Comment (mikaelacaron) [inline Basic-Car-Maintenance/Shared/Dashboard/ViewModels/DashboardViewModel.swift:81]: Delete this print next time, because it's commented out

**Review by mikaelacaron — APPROVED** [review]
Great work!
